# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170216_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
        migrations.AddField(
            model_name='board',
            name='category_set',
            field=models.ManyToManyField(blank=True, to='board.Part'),
        ),
    ]
