# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170216_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category_set',
        ),
        migrations.AddField(
            model_name='board',
            name='category_set',
            field=models.CharField(choices=[('c', 'Chest'), ('s', 'Shoulder'), ('b', 'Back'), ('l', 'Leg'), ('p', 'pack'), ('a', 'Aerobic exercise')], default='a', max_length=1),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
