# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20170216_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
