# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20170216_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='category_set',
            new_name='category',
        ),
    ]
