# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20170216_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('1', '가슴'), ('2', '등'), ('3', '복근'), ('4', '어깨'), ('5', '유산소'), ('6', '하체')], default='a', max_length=1),
        ),
    ]
