# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20170216_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
