# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20170217_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
