# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('1', '스트레칭'), ('2', '유산소운동'), ('3', '근력운동')], default='5', max_length=1),
        ),
    ]
